AWSTemplateFormatVersion: 2010-09-09
Description: This is my gitsync demo template
Resources:
  GitsyncVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.1/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: gitsyncvpc 
  GitsyncSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitsyncVpc
      CidrBlock: 10.0.0.1/24
      Tags:
        - Key: Name
          Value: Git sync
  GitsyncSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitsyncVpc
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: Git sync2